### ISSUE TITLE
setof/3 incorrect

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#233]
[Item#42](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#42)

**Comment by UWN** [comment]
This *is* important.

**Comment by infradig** [comment]
I don't doubt it. It seems to be common problem though, from a common
source.

**Comment by UWN** [comment]
Common? Apart from Scryer, I do not see another system with this problem.

**Comment by infradig** [comment]
B Prolog. CxProlog. Tau Prolog.

**Comment by UWN** [comment]
Thank you, I'm getting sloppy... . But at least I corrected my test cases.

**Comment by UWN** [comment]
Tau works with `setof/3`, but has a bug with handling underscore variables. https://github.com/tau-prolog/tau-prolog/issues/354

**Comment by infradig** [comment]
I've been looking into this. Trealla like a number of systems uses a
version of ROK's aggregates.pl, which I thought may be faulty here. But I
looked at Ciao which behaves correctly, and it does the same (but uses an
older version, I believe, that does assert/retract temporarily). Replacing
Trealla's code with that code and... it's still wrong 😢. That said, I
think the fault is in replace_instance_/5, possibly to do with arg/3.

**Comment by infradig** [comment]
I write the above mainly as a mental note to myself.

**Comment by pmoura** [comment]
I added those two tests to the latest Logtalk git version: https://github.com/LogtalkDotOrg/logtalk3/commit/cc74f9529eb9abfb41726119b5b71c22b112e20a. I bit tricky to adapt given that order of solutions returned by `bagof/3` is undefined per the ISO Prolog Core standard (not to mention having to use `bagof/3` to collect all the solutions to the test goal so that variables are preserved).

**Comment by infradig** [comment]
I have a fix, indeed was arg/3. I thank RO'K for the clue.

**Comment by UWN** [comment]
Now it's

```
?- L=[_,_,_], setof(t,member(E,L),_).
   L = [_A,_,_], E = _, unexpected, unsound.
```
These anonymous underscores in answers are all odd. Sometimes they appear, and sometimes they are named. It would be ideal to have no anonymous underscores in answers, similar to SICStus, Scryer.

**Comment by infradig** [comment]
Yeah, it's coming. But not until tomorrow.

**Comment by pmoura** [comment]
```text
$ logtalk_tester -p trealla
% Batch testing started @ 2023-07-05 23:05:17
%         Logtalk version: 3.68.0-b01
%         Trealla Prolog version: 2.21.16
%
% Documents/Logtalk/logtalk3/tests/prolog/predicates/setof_3
%         40 tests: 2 skipped, 38 passed, 0 failed (0 flaky)
%         completed tests from object tests in 1 second
%         clause coverage n/a
%
% Skipped tests
Documents/Logtalk/logtalk3/tests/prolog/predicates/setof_3/tests.lgt - eddbali_setof_3_25 @ tests
Documents/Logtalk/logtalk3/tests/prolog/predicates/setof_3/tests.lgt - lgt_setof_3_36 @ tests
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 40 tests: 2 skipped, 38 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2023-07-05 23:05:19
```

**Comment by UWN** [comment]
```
?- L=[_,_,_], setof(t,member(E,L),_).
   L = [_A,_B,_C], E = _A
;  L = [_A,_B,_C], E = _B
;  L = [_A,_B,_C], E = _C.
```
It's all perfect, but why and when do you write these intermediary variables? In other words, why not the same as in 

```
?- length(L,3), setof(t,member(E,L),_).
   L = [E,_A,_B]
;  L = [_A,E,_B]
;  L = [_A,_B,E].
```
(Could be, that you treat the underscores as kind-of-named variables)

**Comment by infradig** [comment]
It must be the order the variables are bound.

**Comment by UWN** [comment]
```
?- length(L,3), setof(t,member(E,L),_),L=[_,_,_].
   L = [E,_A,_B]
;  L = [_A,E,_B]
;  L = [_A,_B,E].
?- length(L,3), L=[_,_,_],setof(t,member(E,L),_).
   L = [_A,_B,_C], E = _A
;  L = [_A,_B,_C], E = _B
;  L = [_A,_B,_C], E = _C.
```
What do you mean by *the order the variables are bound*?

**Comment by infradig** [comment]
Yes, one would think these first two would be the same, if not the third as
well..

/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.21.16-dirty
?- length(L,3), setof(t,member(E,L),_).
   L = [E,_A,_B]
;  L = [_A,E,_B]
;  L = [_A,_B,E].
?- L=[_,_,_], setof(t,member(E,L),_).
   L = [_A,_B,_C], E = _A
;  L = [_A,_B,_C], E = _B
;  L = [_A,_B,_C], E = _C.
?- L=[A,B,C], setof(t,member(E,L),_).
   L = [A,B,C], E = A
;  L = [A,B,C], E = B
;  L = [A,B,C], E = C.
?-

**Comment by UWN** [comment]
In the third case, there are three times two named variables which are unified. So in this situation, one has to state that `E = A` or `A = E` &amp;ct. So it is inevitable to have two answer substitutions. But not for the first two cases. (The reason this interests me so much is my suspicion that this differences is somehow induced by the internal representation. So some things that should not be visible, become visible. After all, we have still #216 open.
